version:          "0021a--30-May-2022"
copyright:        "2021-2022"
description:
  This is a
  GitHub Page Template description. 
  See also tagline.
disclaimer:
  I have spoken.
tagline:          "This is a GitHub Page Template tagline"
keywords:         "jekyll, testing"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "Links"
  link:           "/LINKS/"
- navbar:         "Tips"
  link:           "/TIPS/"
- navbar:         "Zip File"
  link:           "/template.zip"
- navbar:         "TarBall"
  link:           "/template.tar.bz2"
- navbar:         "GitHub"
  link:           "https://github.com/yforku/template/"
- navbar:         "Listing"
  link:           "/000.html"
- navbar:         "About"
  link:           "/ABOUT/"
- navbar:         "GitHub Page"
  link:           "https://template.vlsm.org/"
title:            "GitHub Page Template"
lang:             "en-US"
author:           "J. Walker"
address:          "Box 7, Mawitaan, Bangalla."
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/yforku/template/"
google_analytics: "G-KPSLWHN6H7"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

